version: "3"
   
services:
  web:
    build: .
    command: ${RUN_COMMAND}
    user: ${UID}:${UID}

    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - '.env'
  db:
    image: postgres
    user: ${UID}:${UID}
    ports:
      - "5432:5432"
    env_file:
      - '.env'
    volumes:
      - ./data:/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/app/static
    ports:
      - "8001:80"
    depends_on:
      - web