version: "3"
   
services:
  web:
    build: .
    restart: unless-stopped
    command: pipenv run gunicorn djangoproject.wsgi --bind=0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
