# Generated by Django 4.0.1 on 2022-01-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='new', max_length=200),
        ),
    ]
