# Generated by Django 4.0.1 on 2022-01-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_application_set', to='app.application'),
        ),
    ]
